import { TopicContent } from "@/lib/types";

export const topic: TopicContent = {
  id: "5-3",
  blockId: 5,
  title: "try-with-resources",
  summary:
    "Обработка множества IOException, использование try-catch (with resources) для автоматического закрытия потока ввода/вывода. Ресурс должен реализовывать интерфейс AutoCloseable.\n\n---\n\nIntroduced in Java 7, try-with-resources automatically closes AutoCloseable resources when the try block exits, eliminating boilerplate finally blocks and preventing resource leaks.",
  deepDive:
    "Обработка множества IOException, использование try-catch (with resources) для закрытия потока ввода/вывода.\n\nКонструкция try-with-resources автоматически закрывает ресурсы, реализующие интерфейс AutoCloseable, при выходе из блока try. Это избавляет от шаблонного кода в блоке finally и предотвращает утечки ресурсов.\n\nРесурсы закрываются в обратном порядке объявления. Если блок try бросает исключение A, а метод close() бросает исключение B, то A является основным исключением, а B добавляется как подавленное (suppressed) через метод getSuppressed().\n\n---\n\nBefore Java 7, closing resources required verbose finally blocks with null checks and nested try-catch. The try-with-resources statement declares resources in parentheses after the try keyword. Any object implementing AutoCloseable (or its parent Closeable) can be declared here. When the try block completes -- normally or exceptionally -- the close() method is called automatically in reverse declaration order.\n\nA key interview topic is suppressed exceptions. If the try block throws exception A, and close() throws exception B, then A is the primary exception that propagates, and B is added to A's suppressed exceptions array (accessible via getSuppressed()). This is the opposite of the old finally pattern, where the finally exception would mask the original. This design preserves the original cause while still recording cleanup failures.\n\nJava 9 enhanced try-with-resources to allow effectively final variables declared outside the try parentheses: InputStream is = new FileInputStream(path); try (is) { ... }. This removed the requirement that the resource be declared inline. The variable just needs to be effectively final.\n\nUnder the hood, the compiler desugars try-with-resources into a try-finally with proper exception handling and suppression logic. The generated bytecode ensures close() is called even when exceptions occur and correctly chains suppressed exceptions. This is why try-with-resources is strictly superior to manual finally-based cleanup.",
  code: `import java.io.*;

public class TryWithResources {
    // Classic try-with-resources
    public static String readFirstLine(String path) throws IOException {
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            return br.readLine();
        } // br.close() called automatically here
    }

    // Multiple resources - closed in reverse order
    public static void copyFile(String src, String dst) throws IOException {
        try (InputStream in = new FileInputStream(src);
             OutputStream out = new FileOutputStream(dst)) {
            byte[] buf = new byte[8192];
            int n;
            while ((n = in.read(buf)) != -1) {
                out.write(buf, 0, n);
            }
        } // out.close() called first, then in.close()
    }

    // Suppressed exceptions demo
    public static void suppressedDemo() {
        try (AutoCloseable res = () -> {
            throw new RuntimeException("close() failed");
        }) {
            throw new RuntimeException("try block failed");
        } catch (Exception e) {
            System.out.println("Primary: " + e.getMessage());
            for (Throwable s : e.getSuppressed()) {
                System.out.println("Suppressed: " + s.getMessage());
            }
        }
        // Output:
        // Primary: try block failed
        // Suppressed: close() failed
    }

    // Java 9+: effectively final variable
    public static void java9Style(String path) throws IOException {
        BufferedReader br = new BufferedReader(new FileReader(path));
        try (br) { // valid since Java 9
            System.out.println(br.readLine());
        }
    }
}`,
  interviewQs: [
    {
      id: "5-3-q0",
      q: "What interface must a class implement to be used with try-with-resources?",
      a: "The class must implement AutoCloseable (or its sub-interface Closeable). AutoCloseable declares a single close() method that throws Exception. Closeable (from java.io) is a sub-interface that narrows the throws clause to IOException. All standard I/O classes, JDBC Connection/Statement/ResultSet, and many other resource types implement one of these interfaces.",
      difficulty: "junior",
    },
    {
      id: "5-3-q1",
      q: "What happens when both the try block and the close() method throw exceptions?",
      a: "The exception from the try block is the primary exception that propagates to the caller. The exception from close() becomes a suppressed exception, attached to the primary exception via addSuppressed(). You can retrieve suppressed exceptions with getSuppressed(). This is the opposite of the old finally pattern, where the cleanup exception would mask the original error. This design ensures you never lose the root cause.",
      difficulty: "mid",
    },
    {
      id: "5-3-q2",
      q: "How does the compiler desugar try-with-resources, and what changed in Java 9?",
      a: "The compiler transforms try-with-resources into nested try-finally blocks. The generated code: (1) stores the resource reference, (2) wraps the body in a try block, (3) in the finally, checks if the resource is non-null, (4) if the body threw, calls close() in a nested try-catch and adds any close exception as suppressed, (5) if the body didn't throw, calls close() normally. Java 9 removed the requirement that resources be declared inline in the try parentheses. Now effectively final variables can be used directly, reducing redundancy when resources are created earlier in the method. The bytecode generated is identical in both cases.",
      difficulty: "senior",
    },
  ],
  tip: "Always prefer try-with-resources over try-finally for resource management. In interviews, mention suppressed exceptions -- most candidates forget this detail, and it shows deep understanding.",
  springConnection: {
    concept: "try-with-resources",
    springFeature: "JdbcTemplate",
    explanation:
      "Spring's JdbcTemplate internally uses try-with-resources to manage JDBC Connection, Statement, and ResultSet objects. This is why you never need to manually close database resources when using Spring's data access abstractions -- the template handles it correctly, including proper exception translation.",
  },
};
