import { TopicContent } from "@/lib/types";

export const topic: TopicContent = {
  id: "6-5",
  blockId: 6,
  title: "Generics & Type Erasure",
  summary:
    "Java generics provide compile-time type safety for collections and APIs. However, due to type erasure, generic type information is removed at runtime -- the JVM sees only raw types. Understanding erasure is essential for avoiding ClassCastException pitfalls and acing interviews.",
  deepDive:
    "Generics were introduced in Java 5 to eliminate unsafe casts and catch type errors at compile time. List<String> tells the compiler that only Strings are allowed, and the compiler inserts the necessary casts automatically. However, to maintain backward compatibility with pre-generics code, Java implements generics through type erasure: the compiler removes all generic type parameters and replaces them with their bounds (or Object if unbounded) during compilation.\n\nThis means List<String> and List<Integer> are both just List at runtime. The JVM has no knowledge of generic type arguments. Consequences: (1) you cannot use instanceof with parameterized types (list instanceof List<String> won't compile), (2) you cannot create generic arrays (new T[] is illegal), (3) you cannot call new T() without a Class<T> token, (4) you cannot overload methods that differ only by generic parameter (void process(List<String>) and void process(List<Integer>) have the same erasure). Bridge methods are generated by the compiler to maintain polymorphism after erasure.\n\nGeneric methods declare type parameters before the return type: <T> T firstElement(List<T> list). Bounded types restrict what T can be: <T extends Comparable<T>> constrains T to types implementing Comparable. Multiple bounds use &: <T extends Serializable & Comparable<T>>. Note: extends is used for both class and interface bounds in generics.\n\nReification workarounds: when you need type information at runtime, pass a Class<T> token (common in frameworks), use TypeReference/TypeToken patterns (Jackson, Gson), or use anonymous subclasses that capture generic types in their bytecode via getGenericSuperclass(). Spring's ParameterizedTypeReference uses this trick for RestTemplate calls with generic response types.",
  code: `import java.util.*;
import java.lang.reflect.*;

public class GenericsDemo {
    // Generic method with bounded type parameter
    public static <T extends Comparable<T>> T max(T a, T b) {
        return a.compareTo(b) >= 0 ? a : b;
    }

    // Multiple bounds: T must be Serializable AND Comparable
    public static <T extends Serializable & Comparable<T>> void process(T item) {
        System.out.println("Processing: " + item);
    }

    // Class<T> token to work around erasure
    public static <T> T createInstance(Class<T> clazz) throws Exception {
        return clazz.getDeclaredConstructor().newInstance();
    }

    // Type erasure consequences
    public static void erasureDemo() {
        List<String> strings = new ArrayList<>();
        List<Integer> ints = new ArrayList<>();

        // Both are just "ArrayList" at runtime
        System.out.println(strings.getClass() == ints.getClass()); // true!

        // Cannot do: if (strings instanceof List<String>) -- won't compile
        // Cannot do: new T[10] -- generic array creation is illegal
        // Cannot do: new T() -- type parameter cannot be instantiated

        // Raw type escape hatch (UNSAFE, compiler warning)
        List rawList = strings;
        rawList.add(42); // compiles! No type checking at runtime
        // String s = strings.get(0); // ClassCastException at runtime!
    }

    // Capturing generic type info via anonymous subclass
    static abstract class TypeRef<T> {
        Type getType() {
            return ((ParameterizedType) getClass()
                .getGenericSuperclass()).getActualTypeArguments()[0];
        }
    }

    public static void main(String[] args) throws Exception {
        System.out.println(max("apple", "banana")); // "banana"

        String s = createInstance(String.class);

        // TypeRef captures List<String> in bytecode
        TypeRef<List<String>> ref = new TypeRef<>() {};
        System.out.println(ref.getType()); // java.util.List<java.lang.String>
    }
}`,
  interviewQs: [
    {
      id: "6-5-q0",
      q: "What is type erasure and why does Java use it?",
      a: "Type erasure means the compiler removes all generic type information during compilation. List<String> becomes just List in the bytecode. Java uses erasure to maintain backward compatibility with pre-generics code (Java 1.4 and earlier). This means old code using raw List can work seamlessly with new code using List<String>. The downside is that generic type information is unavailable at runtime, preventing operations like instanceof checks with type parameters or creating generic arrays.",
      difficulty: "junior",
    },
    {
      id: "6-5-q1",
      q: "Why can't you create a generic array like new T[] in Java?",
      a: "Arrays in Java are reified -- they know and enforce their component type at runtime (String[] rejects Integer via ArrayStoreException). Generics are erased -- T becomes Object at runtime. If new T[] were allowed, it would create an Object[] that could accept any type, violating the array's runtime type guarantee. The compiler prevents this to avoid heap pollution where a variable of type T[] actually holds elements of the wrong type. Workarounds include: Arrays.newInstance(clazz, size) with a Class<T> token, or using List<T> instead of arrays with generics.",
      difficulty: "mid",
    },
    {
      id: "6-5-q2",
      q: "Explain bridge methods in Java generics. When are they generated and why?",
      a: "Bridge methods are synthetic methods generated by the compiler to preserve polymorphism after type erasure. Example: if class StringList extends ArrayList<String> and overrides get(int) to return String, after erasure ArrayList.get returns Object. The compiler generates a bridge method with signature Object get(int) that calls String get(int), maintaining the virtual dispatch contract. Without the bridge, the JVM would not see the override because the erased signatures differ. Bridge methods are marked ACC_BRIDGE and ACC_SYNTHETIC in bytecode. You can detect them via Method.isBridge(). They also appear when covariant return types interact with generics.",
      difficulty: "senior",
    },
  ],
  tip: "In interviews, show you understand the practical impact of erasure: 'List<String> and List<Integer> are the same class at runtime. If you need runtime type info, pass a Class<T> token.' This bridges theory and practice.",
  springConnection: {
    concept: "Generics & Type Erasure",
    springFeature: "Spring's ParameterizedTypeReference and ResolvableType",
    explanation:
      "Spring's ParameterizedTypeReference<List<User>> captures generic types at runtime using the anonymous subclass trick to bypass type erasure. Spring's ResolvableType provides a full API for introspecting generic types. These are essential in Spring WebClient, RestTemplate, and the entire Spring Data repository infrastructure where generic type information drives query generation and result mapping.",
  },
};
